version: "3.7"
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=red_interna
        networks:
            - red_interna
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy_data:/data
        restart: unless-stopped

networks:
    red_interna:
        external: true

volumes:
    caddy_data: {}