version: '3.8'

services:
  openldap:
    container_name: ldap
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: "example.org"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    networks:
      - red_interna

volumes:
  openldap_data:
    driver: local
  openldap_config:
    driver: local

networks:
  red_interna:
    external: true