Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"  #Selecciona y descarga la última versión de debian12
  config.vm.synced_folder "./dnsmasq", "/dnsmasq" #Monta el volúmen de la MV en el directorio del contenedor
  config.vm.provision "shell", path: "provision.sh" #Ejecuta el contenido del archivo provision.sh en la máquina recién creada
  config.vm.network "public_network" #Conecta a la máquina virtual con el router del ordenador
  # Vincula el puerto 53 de la VM al puerto 53 de la máquina anfitriona (host)
  config.vm.network "forwarded_port", guest: 53, host: 53, protocol: "udp"
  config.vm.network "forwarded_port", guest: 53, host: 53, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 5380, host: 5380, protocol: "tcp"
end